- name: Deploy with pam config
  hosts: default
  become: true
  tasks:
    - name: Install epel-release
      yum:
        name:
          - epel-release
        state: present
      tags:
        - required_packages
